import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { ColumnDef } from "@tanstack/react-table";
import { Edit, Plus, Star, ToggleLeft, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { SettingTypeBadge, StatusBadge } from "@/components/admin/Badges";
import { MediaUploader } from "@/components/admin/MediaUploader";
import { ServerTable } from "@/components/admin/ServerTable";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input, Select, Textarea } from "@/components/ui/field";
import { Modal } from "@/components/ui/modal";
import { api } from "@/lib/api";
import { settingTypeLabels } from "@/lib/labels";
import type { Department, Language, MediaAsset, PagedResult, ResourceContentLanguage, SettingType, SiteSetting, TeamMember } from "@/types/api";

type Tab = "languages" | "departments" | "team" | "settings" | "resources";

function LanguageEditor({ open, language, onClose }: { open: boolean; language?: Language | null; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ code: "", cultureCode: "", name: "", nativeName: "", sortOrder: "0", isActive: true, isDefault: false });
  useEffect(() => { if (!open) return; setForm(language ? { code: language.code, cultureCode: language.cultureCode, name: language.name, nativeName: language.nativeName, sortOrder: String(language.sortOrder), isActive: language.isActive, isDefault: language.isDefault } : { code: "", cultureCode: "", name: "", nativeName: "", sortOrder: "0", isActive: true, isDefault: false }); }, [language, open]);
  const save = useMutation({ mutationFn: () => api.put("/admin/languages", { id: language?.id, ...form, sortOrder: Number(form.sortOrder || 0) }), onSuccess: () => { toast.success("Language saved."); void queryClient.invalidateQueries(); onClose(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Language save failed.") });
  return <Modal open={open} title={language ? "Edit language" : "Create language"} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!form.code || !form.cultureCode || !form.name || save.isPending} onClick={() => save.mutate()}>Save language</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Code"><Input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></Field><Field label="Culture code"><Input value={form.cultureCode} onChange={(e) => setForm({ ...form, cultureCode: e.target.value })} /></Field><Field label="Name"><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Native name"><Input value={form.nativeName} onChange={(e) => setForm({ ...form, nativeName: e.target.value })} /></Field><Field label="Sort order"><Input type="number" value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: e.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} /> Active</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isDefault} onChange={(e) => setForm({ ...form, isDefault: e.target.checked })} /> Default</label></div></Modal>;
}

function DepartmentEditor({ open, department, onClose }: { open: boolean; department?: Department | null; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [name, setName] = useState("");
  const [sortOrder, setSortOrder] = useState("0");
  const [isActive, setIsActive] = useState(true);
  useEffect(() => { if (!open) return; setName(department?.name ?? ""); setSortOrder(String(department?.sortOrder ?? 0)); setIsActive(department?.isActive ?? true); }, [department, open]);
  const save = useMutation({ mutationFn: () => api.put("/admin/departments", { id: department?.id, sortOrder: Number(sortOrder || 0), isActive, translations: [{ language: "en", name }] }), onSuccess: () => { toast.success("Department saved."); void queryClient.invalidateQueries(); onClose(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Department save failed.") });
  return <Modal open={open} title={department ? "Edit department" : "Create department"} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!name || save.isPending} onClick={() => save.mutate()}>Save department</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><Input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Sort order"><Input type="number" value={sortOrder} onChange={(e) => setSortOrder(e.target.value)} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} /> Active</label></div></Modal>;
}

function TeamEditor({ open, member, onClose }: { open: boolean; member?: TeamMember | null; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ firstName: "", lastName: "", position: "", departmentId: "", email: "", bio: "", photoPath: "", sortOrder: "0", isActive: true });
  const departments = useQuery({ queryKey: ["departments-select"], queryFn: () => api.get<PagedResult<Department>>("/admin/departments", { pageNumber: 1, pageSize: 100, language: "en" }) });
  useEffect(() => { if (!open) return; setForm(member ? { firstName: member.firstName, lastName: member.lastName, position: member.position, departmentId: member.departmentId?.toString() ?? "", email: member.email, bio: member.bio ?? "", photoPath: member.photoPath ?? "", sortOrder: String(member.sortOrder), isActive: member.isActive } : { firstName: "", lastName: "", position: "", departmentId: "", email: "", bio: "", photoPath: "", sortOrder: "0", isActive: true }); }, [member, open]);
  const save = useMutation({ mutationFn: () => api.put("/admin/team-members", { id: member?.id, ...form, departmentId: form.departmentId ? Number(form.departmentId) : null, sortOrder: Number(form.sortOrder || 0) }), onSuccess: () => { toast.success("Team member saved."); void queryClient.invalidateQueries(); onClose(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Team member save failed.") });
  const uploaded = (asset: MediaAsset) => setForm((current) => ({ ...current, photoPath: asset.imagePath }));
  return <Modal open={open} wide title={member ? "Edit team member" : "Create team member"} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!form.firstName || !form.lastName || !form.position || !form.email || save.isPending} onClick={() => save.mutate()}>Save member</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="First name"><Input value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} /></Field><Field label="Last name"><Input value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} /></Field><Field label="Position"><Input value={form.position} onChange={(e) => setForm({ ...form, position: e.target.value })} /></Field><Field label="Email"><Input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Department"><Select value={form.departmentId} onChange={(e) => setForm({ ...form, departmentId: e.target.value })}><option value="">No department</option>{departments.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Sort order"><Input type="number" value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: e.target.value })} /></Field><div className="sm:col-span-2"><Field label="Photo path"><Input value={form.photoPath} onChange={(e) => setForm({ ...form, photoPath: e.target.value })} /></Field><div className="mt-2"><MediaUploader folderName="team" onUploaded={uploaded} buttonLabel="Upload photo" /></div></div><div className="sm:col-span-2"><Field label="Bio"><Textarea value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /></Field></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} /> Active</label></div></Modal>;
}

function SettingEditor({ open, setting, onClose }: { open: boolean; setting?: SiteSetting | null; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ key: "", value: "", description: "", category: "", iconClass: "", sortOrder: "0", type: 0 as SettingType, isActive: true });
  useEffect(() => { if (!open) return; setForm(setting ? { key: setting.key, value: setting.value ?? "", description: setting.description ?? "", category: setting.category ?? "", iconClass: setting.iconClass ?? "", sortOrder: String(setting.sortOrder), type: setting.type, isActive: setting.isActive } : { key: "", value: "", description: "", category: "", iconClass: "", sortOrder: "0", type: 0, isActive: true }); }, [setting, open]);
  const save = useMutation({ mutationFn: () => api.put("/admin/settings", { id: setting?.id, ...form, value: form.value || null, description: form.description || null, category: form.category || null, iconClass: form.iconClass || null, sortOrder: Number(form.sortOrder || 0) }), onSuccess: () => { toast.success("Setting saved."); void queryClient.invalidateQueries(); onClose(); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Setting save failed.") });
  return <Modal open={open} title={setting ? "Edit setting" : "Create setting"} onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!form.key || save.isPending} onClick={() => save.mutate()}>Save setting</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="Key"><Input value={form.key} onChange={(e) => setForm({ ...form, key: e.target.value })} /></Field><Field label="Category"><Input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></Field><Field label="Type"><Select value={form.type} onChange={(e) => setForm({ ...form, type: Number(e.target.value) as SettingType })}>{Object.entries(settingTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Sort order"><Input type="number" value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: e.target.value })} /></Field><div className="sm:col-span-2"><Field label="Value"><Textarea value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} /></Field></div><div className="sm:col-span-2"><Field label="Description"><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} /> Active</label></div></Modal>;
}

function ResourcesPanel() {
  const resources = useQuery({ queryKey: ["resource-languages"], queryFn: () => api.get<ResourceContentLanguage[]>("/admin/resources/languages") });
  return <Card><CardHeader><CardTitle>Resource languages</CardTitle><CardDescription>Validation state for website content resource files.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{resources.data?.map((item) => <div key={item.cultureCode} className="rounded-md border border-border bg-background p-4"><p className="font-medium">{item.cultureCode}</p><div className="mt-2"><Badge variant={item.isValid ? "success" : "danger"}>{item.isValid ? "Valid" : "Needs attention"}</Badge></div></div>)}{!resources.data?.length ? <p className="text-sm text-muted-foreground">No resource files found.</p> : null}</div></CardContent></Card>;
}

export function OperationsPage() {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<Tab>("languages");
  const [language, setLanguage] = useState<Language | null>(null); const [newLanguage, setNewLanguage] = useState(false);
  const [department, setDepartment] = useState<Department | null>(null); const [newDepartment, setNewDepartment] = useState(false);
  const [member, setMember] = useState<TeamMember | null>(null); const [newMember, setNewMember] = useState(false);
  const [setting, setSetting] = useState<SiteSetting | null>(null); const [newSetting, setNewSetting] = useState(false);
  const deleteLanguage = useMutation({ mutationFn: (id: number) => api.delete(`/admin/languages/${id}`), onSuccess: () => { toast.success("Language deleted."); void queryClient.invalidateQueries(); }, onError: (e) => toast.error(e instanceof Error ? e.message : "Delete failed.") });
  const setDefault = useMutation({ mutationFn: (id: number) => api.patch(`/admin/languages/${id}/default`), onSuccess: () => { toast.success("Default language updated."); void queryClient.invalidateQueries(); } });
  const toggleLanguage = useMutation({ mutationFn: (id: number) => api.patch(`/admin/languages/${id}/toggle-status`), onSuccess: () => { toast.success("Language status updated."); void queryClient.invalidateQueries(); } });
  const deleteDepartment = useMutation({ mutationFn: (id: number) => api.delete(`/admin/departments/${id}`), onSuccess: () => { toast.success("Department deleted."); void queryClient.invalidateQueries(); } });
  const deleteMember = useMutation({ mutationFn: (id: number) => api.delete(`/admin/team-members/${id}`), onSuccess: () => { toast.success("Team member deleted."); void queryClient.invalidateQueries(); } });
  const deleteSetting = useMutation({ mutationFn: (id: number) => api.delete(`/admin/settings/${id}`), onSuccess: () => { toast.success("Setting deleted."); void queryClient.invalidateQueries(); } });

  const languageColumns = useMemo<ColumnDef<Language>[]>(() => [{ accessorKey: "name", header: "Language", cell: ({ row }) => <div><p className="font-medium">{row.original.name}</p><p className="text-xs text-muted-foreground">{row.original.code} · {row.original.cultureCode}</p></div> }, { accessorKey: "isActive", header: "Status", cell: ({ row }) => <div className="flex gap-2"><StatusBadge active={row.original.isActive} />{row.original.isDefault ? <Badge variant="default">Default</Badge> : null}</div> }, { id: "actions", header: "Actions", cell: ({ row }) => <div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setLanguage(row.original)}><Edit className="h-4 w-4" />Edit</Button><Button size="sm" variant="secondary" onClick={() => setDefault.mutate(row.original.id)}><Star className="h-4 w-4" />Default</Button><Button size="sm" variant="secondary" onClick={() => toggleLanguage.mutate(row.original.id)}><ToggleLeft className="h-4 w-4" />Toggle</Button><Button size="sm" variant="destructive" onClick={() => deleteLanguage.mutate(row.original.id)}><Trash2 className="h-4 w-4" />Delete</Button></div> }], [deleteLanguage, setDefault, toggleLanguage]);
  const departmentColumns = useMemo<ColumnDef<Department>[]>(() => [{ accessorKey: "name", header: "Department" }, { accessorKey: "sortOrder", header: "Sort" }, { accessorKey: "isActive", header: "Status", cell: ({ row }) => <StatusBadge active={row.original.isActive} /> }, { id: "actions", header: "Actions", cell: ({ row }) => <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => setDepartment(row.original)}><Edit className="h-4 w-4" />Edit</Button><Button size="sm" variant="destructive" onClick={() => deleteDepartment.mutate(row.original.id)}><Trash2 className="h-4 w-4" />Delete</Button></div> }], [deleteDepartment]);
  const teamColumns = useMemo<ColumnDef<TeamMember>[]>(() => [{ accessorKey: "fullName", header: "Member", cell: ({ row }) => <div><p className="font-medium">{row.original.fullName}</p><p className="text-xs text-muted-foreground">{row.original.position}</p></div> }, { accessorKey: "departmentName", header: "Department" }, { accessorKey: "email", header: "Email" }, { accessorKey: "isActive", header: "Status", cell: ({ row }) => <StatusBadge active={row.original.isActive} /> }, { id: "actions", header: "Actions", cell: ({ row }) => <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => setMember(row.original)}><Edit className="h-4 w-4" />Edit</Button><Button size="sm" variant="destructive" onClick={() => deleteMember.mutate(row.original.id)}><Trash2 className="h-4 w-4" />Delete</Button></div> }], [deleteMember]);
  const settingColumns = useMemo<ColumnDef<SiteSetting>[]>(() => [{ accessorKey: "key", header: "Key", cell: ({ row }) => <div><p className="font-medium">{row.original.key}</p><p className="text-xs text-muted-foreground">{row.original.category ?? "General"}</p></div> }, { accessorKey: "type", header: "Type", cell: ({ row }) => <SettingTypeBadge type={row.original.type} /> }, { accessorKey: "isActive", header: "Status", cell: ({ row }) => <StatusBadge active={row.original.isActive} /> }, { id: "actions", header: "Actions", cell: ({ row }) => <div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => setSetting(row.original)}><Edit className="h-4 w-4" />Edit</Button><Button size="sm" variant="destructive" onClick={() => deleteSetting.mutate(row.original.id)}><Trash2 className="h-4 w-4" />Delete</Button></div> }], [deleteSetting]);
  const tabs: { value: Tab; label: string }[] = [{ value: "languages", label: "Languages" }, { value: "departments", label: "Departments" }, { value: "team", label: "Team" }, { value: "settings", label: "Settings" }, { value: "resources", label: "Resources" }];
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="font-display text-4xl font-semibold">Operations</h1><p className="text-sm text-muted-foreground">Manage multilingual and operational website data.</p></div><div className="flex flex-wrap gap-2">{tabs.map((item) => <Button key={item.value} variant={tab === item.value ? "default" : "secondary"} onClick={() => setTab(item.value)}>{item.label}</Button>)}</div></div>{tab === "languages" ? <ServerTable<Language> title="Languages" endpoint="/admin/languages" queryKey="languages" columns={languageColumns} toolbar={<Button size="sm" onClick={() => setNewLanguage(true)}><Plus className="h-4 w-4" />New language</Button>} /> : null}{tab === "departments" ? <ServerTable<Department> title="Departments" endpoint="/admin/departments" queryKey="departments" columns={departmentColumns} defaultQuery={{ language: "en" }} toolbar={<Button size="sm" onClick={() => setNewDepartment(true)}><Plus className="h-4 w-4" />New department</Button>} /> : null}{tab === "team" ? <ServerTable<TeamMember> title="Team members" endpoint="/admin/team-members" queryKey="team-members" columns={teamColumns} toolbar={<Button size="sm" onClick={() => setNewMember(true)}><Plus className="h-4 w-4" />New member</Button>} /> : null}{tab === "settings" ? <ServerTable<SiteSetting> title="Site settings" endpoint="/admin/settings" queryKey="site-settings" columns={settingColumns} toolbar={<Button size="sm" onClick={() => setNewSetting(true)}><Plus className="h-4 w-4" />New setting</Button>} /> : null}{tab === "resources" ? <ResourcesPanel /> : null}<LanguageEditor open={newLanguage || Boolean(language)} language={language} onClose={() => { setNewLanguage(false); setLanguage(null); }} /><DepartmentEditor open={newDepartment || Boolean(department)} department={department} onClose={() => { setNewDepartment(false); setDepartment(null); }} /><TeamEditor open={newMember || Boolean(member)} member={member} onClose={() => { setNewMember(false); setMember(null); }} /><SettingEditor open={newSetting || Boolean(setting)} setting={setting} onClose={() => { setNewSetting(false); setSetting(null); }} /></div>;
}